export const property = [
  {
    id: 1,
    image:
      "https://www.crescent-builders.com/blog/wp-content/uploads/2021/07/Handshake-over-Property-Deal.original-e1619002308793.jpg",
    address: "Ghatkopar Mumbai",
    email: "radam@gmail.com",
    phoneNumber: "9123456781",
  },
  {
    id: 2,
    image:
      "https://www.croatia-property.net/wp-content/uploads/2017/06/How-to-buy-property-in-Croatia-1080x648.jpg",
    address: "Bandra, Mumbai",
    email: "john.doe@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 3,
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCCxT3HP_RYyCJcpvrp2xzolANSzIFELUPXcVEx5v6k_DHPq77zLGB6x-7tRFA3bS_PzE&usqp=CAU",
    address: "Powai, Mumbai",
    email: "jane.doe@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 4,
    image:
      "https://www.investopedia.com/thmb/Hi0eZk07zVS2rGHRlm2BOwpfDuI=/800x533/filters:no_upscale():max_bytes(150000):strip_icc()/CreditKarmaHomeInvestopediaDesktop-851a9ea5966a49e99e9f8ef844c533a3.jpg",
    address: "Andheri, Mumbai",
    email: "sam.smith@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 5,
    image: "https://example.com/image5.jpg",
    address: "Malad, Mumbai",
    email: "sara.jones@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 6,
    image: "https://example.com/image6.jpg",
    address: "Colaba, Mumbai",
    email: "mike.johnson@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 7,
    image: "https://example.com/image7.jpg",
    address: "Vashi, Mumbai",
    email: "emily.brown@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 8,
    image: "https://example.com/image8.jpg",
    address: "Thane, Mumbai",
    email: "david.wilson@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 9,
    image: "https://example.com/image9.jpg",
    address: "Dadar, Mumbai",
    email: "lisa.miller@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 10,
    image: "https://example.com/image10.jpg",
    address: "Chembur, Mumbai",
    email: "chris.davis@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 11,
    image: "https://example.com/image11.jpg",
    address: "Worli, Mumbai",
    email: "amanda.white@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 12,
    image: "https://example.com/image12.jpg",
    address: "Kurla, Mumbai",
    email: "matt.thompson@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 13,
    image: "https://example.com/image13.jpg",
    address: "Borivali, Mumbai",
    email: "jessica.martin@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 14,
    image: "https://example.com/image14.jpg",
    address: "Juhu, Mumbai",
    email: "jason.lewis@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 15,
    image: "https://example.com/image15.jpg",
    address: "Kandivali, Mumbai",
    email: "olivia.baker@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 16,
    image: "https://example.com/image16.jpg",
    address: "Mulund, Mumbai",
    email: "ryan.kelly@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 17,
    image: "https://example.com/image17.jpg",
    address: "Santacruz, Mumbai",
    email: "sophia.cooper@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 18,
    image: "https://example.com/image18.jpg",
    address: "Churchgate, Mumbai",
    email: "nathan.roberts@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 19,
    image: "https://example.com/image19.jpg",
    address: "Versova, Mumbai",
    email: "madison.wright@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 20,
    image: "https://example.com/image20.jpg",
    address: "Marine Lines, Mumbai",
    email: "andrew.hall@example.com",
    phoneNumber: "0987654321",
  },
  {
    id: 21,
    image: "https://example.com/image21.jpg",
    address: "Byculla, Mumbai",
    email: "hannah.edwards@example.com",
    phoneNumber: "0987654321",
  },
];
